name: "EasyScript"
version: "1.0"
main: "org.cyberiantiger.minecraft.easyscript.EasyScript"
website: "http://cyberiantiger.org/EasyScript/"
commands:
  script:
    description: Execute a script
    usage: /script <name> <args>
    permission: easyscript.script
  scriptreload:
    description: Recompile scripts
    usage: /scriptreload
    permission: easyscript.reload